name: nav_frame
description: "navigation app for frames"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  logging: ^1.3.0
  simple_frame_app: ^3.1.0
  intl: ^0.17.0 # Or the latest version
  async: ^2.11.0
  opencv_dart: ^1.3.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/simple_frame_app/lua/battery.min.lua
    - packages/simple_frame_app/lua/data.min.lua
    - packages/simple_frame_app/lua/code.min.lua
    - packages/simple_frame_app/lua/plain_text.min.lua
    - packages/simple_frame_app/lua/camera.min.lua
    - packages/simple_frame_app/lua/image_sprite_block.min.lua
    - assets/frame_app.lua
    - assets/maps_route_easy.jpg
